name: sync-sheets

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create data directory
      run: mkdir -p data
      
    - name: Fetch orders from Google Sheets
      run: |
        curl -s -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" "https://script.google.com/macros/s/AKfycbwDM7VQdfNc8ADsJEL81Z1bW1JWjZ_-8LFJa3AaZFuQf0rO4ojc5OMJ97GKjTnNPbI9ng/exec?action=exportOrders" > data/orders.json
        curl -s -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" "https://script.google.com/macros/s/AKfycbwDM7VQdfNc8ADsJEL81Z1bW1JWjZ_-8LFJa3AaZFuQf0rO4ojc5OMJ97GKjTnNPbI9ng/exec?action=exportRSVPs" > data/rsvps.json
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/orders.json data/rsvps.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync sheet data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
